# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2026 Saul St John (W9SSJ)

"""Locate the ARDOP ground-truth artifacts under ``working/ardop/reference/``.

Per the project's reading discipline (``working/ardop/reference/README.md``)
nothing under ``reference/`` is copied into besra. The reference implementations
ship byte-exact validation artifacts, and besra's tests read them *in place*:

- ``ardop-reference-vectors.txt`` — CRC-16 / CRC-8 / frame-type-parity / RS
  vectors generated by compiling ardopcf's verbatim functions.
- ``txframe-manifest.txt`` + ``txframe_*.wav`` — one ground-truth audio render
  per frame type, keyed to its ``(frame-type, session-id, payload)``.

Tests skip cleanly when the reference tree is absent (a fresh clone without the
git-ignored references), exactly as the reference's own oracle tests skip
without their binary — so the suite stays hermetic.
"""

from __future__ import annotations

import wave
from pathlib import Path

import numpy as np
import pytest

from hfmodem.tests import evidence
_REFERENCE = evidence.WORKING / "ardop" / "reference"

#: The clone the renders come out of, named on its own because its presence is what
#: separates "never cloned" from "cloned and since lost a file" — see
#: `reference_renders` below.
REFERENCE_TREE = _REFERENCE / "M0LTE.Ardop"
REFERENCE_CLONE = "git clone https://github.com/M0LTE/M0LTE.Ardop.git"

_FIXTURES = REFERENCE_TREE / "tests" / "M0LTE.Ardop.Tests" / "Fixtures"
VECTORS = _FIXTURES / "ardop-reference-vectors.txt"
MANIFEST = _FIXTURES / "txframe-manifest.txt"
_ARDOPCF = _REFERENCE / "ardopcf"

HAVE = _FIXTURES.is_dir()

requires_reference = pytest.mark.skipif(
    not HAVE, reason="reference/ ground-truth tree not present (git-ignored)")


def reference_vectors(kind: str) -> list[list[str]]:
    """Parsed lines of one kind from ``ardop-reference-vectors.txt``
    (``crc16`` | ``crc8`` | ``parity`` | ``rs``), as token lists sans the kind."""
    out = []
    for line in VECTORS.read_text().splitlines():
        if line.startswith("#") or not line:
            continue
        parts = line.split()
        if parts[0] == kind:
            out.append(parts[1:])
    return out


def txframe_manifest() -> dict[str, dict]:
    """``{wav_name: {type, session_id, payload|meta}}`` from the manifest.

    ``payload`` is bytes for data frames; control frames carry a ``meta`` dict
    (``timing=`` / ``sn=,quality=`` / ``caller=,target=,grid=``) or nothing."""
    out: dict[str, dict] = {}
    for line in MANIFEST.read_text().splitlines():
        if line.startswith("#") or not line:
            continue
        name, ftype, sid, extra = line.split()[:4]
        entry = {"type": int(ftype, 16), "session_id": int(sid, 16)}
        if extra == "-":
            entry["payload"] = b""
        elif all(c in "0123456789ABCDEFabcdef" for c in extra):
            entry["payload"] = bytes.fromhex(extra)
        else:
            entry["meta"] = dict(kv.split("=", 1) for kv in extra.split(","))
        out[name] = entry
    return out


def matches(frame, entry: dict) -> bool:
    """Whether a decoded frame is the manifest entry, payload/metadata included.

    The boolean form for tests that count successes over many noise realizations;
    the clean-path tests assert field by field for the better diagnostic."""
    if frame is None or not frame.ok or frame.type != entry["type"]:
        return False
    meta = entry.get("meta")
    if "payload" in entry:
        return frame.payload == entry["payload"]
    if meta is None:
        return frame.payload == b""
    if "timing" in meta:
        return frame.conack_timing_ms == int(meta["timing"])
    if "sn" in meta:
        return (frame.pingack_sn_db == int(meta["sn"])
                and frame.pingack_quality == int(meta["quality"]))
    if "grid" in meta:
        return frame.caller == meta["caller"] and frame.grid == meta["grid"]
    return frame.caller == meta["caller"] and frame.target == meta["target"]


def load_wav(name: str) -> np.ndarray:
    """A ground-truth ``txframe_*.wav`` as int16 mono samples (12 kHz)."""
    with wave.open(str(_FIXTURES / name)) as w:
        assert w.getframerate() == 12000 and w.getnchannels() == 1
        return np.frombuffer(w.readframes(w.getnframes()), dtype="<i2")


def wav_names() -> list[str]:
    """The ground-truth renders, or none of them when the tree is absent.

    Read at COLLECTION time by ``parametrize``, which is before any ``skipif``
    can fire — so an absent reference tree has to be a value here rather than the
    FileNotFoundError that used to abort collection of the whole distribution.
    """
    return sorted(txframe_manifest()) if HAVE else []


def wav_params() -> list:
    """``wav_names()`` for ``parametrize``, naming what is missing when empty.

    An empty parameter set makes pytest report "got empty parameter set", which
    says a test did not run without saying what would turn it on. The placeholder
    carries the same skip reason as every other gate in this module.
    """
    return wav_names() or [pytest.param("", marks=requires_reference)]


def reference_renders() -> tuple[Path, ...]:
    """Every artifact the reference tree has to hold for besra to be measured at all.

    A skip is the right answer for a tree that never cloned it and the wrong one
    for a tree that did and has since lost a file, and nothing here can tell those
    apart — so the distinction is drawn once, in `tests/gates/test_corpus_present.py`,
    which reads this. It is what `RF_CORPUS_RECORDINGS` is for kestrel and
    `COMMITTED` is for shrike, and its absence is why 236 besra outcomes existed
    only on the machine that happened to have the clone.

    The renders are listed off the manifest rather than globbed: a `txframe_*.wav`
    the manifest does not name is not evidence, and one it names that is not on
    disk is the hole.
    """
    if not MANIFEST.exists():
        return (VECTORS, MANIFEST)
    return (VECTORS, MANIFEST, *(_FIXTURES / n for n in txframe_manifest()))


def ardopcf_dir() -> Path:
    return _ARDOPCF
