# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2026 Saul St John (W9SSJ)

"""Build embedded figure data from implementation tables and recorded audio.

    python docs/viz/build.py          # update figure blocks
    python docs/viz/build.py --check  # verify the embedded values

The comparison and mode pages contain delimited JSON blocks so their figures
work offline. Source data includes ARDOP recordings in the test fixtures and
the mode implementation tables. Pages absent from a reduced source tree are
reported and skipped.
"""
from __future__ import annotations

import argparse
import base64
import json
import sys
import wave
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[2]
FIXTURES = REPO / "packages/hfmodem/hfmodem/tests/besra/fixtures"

BEGIN = "/* ---- generated by docs/viz/build.py; do not edit by hand ---- */"
END = "/* ---- end generated ---- */"


def _wav(path: Path) -> tuple[int, np.ndarray]:
    with wave.open(str(path)) as w:
        return w.getframerate(), np.frombuffer(w.readframes(w.getnframes()), "<i2")


def _pack(a: np.ndarray) -> str:
    """A uint8 array as plain base64.

    Deflating it first saved 7% and cost the page a `DecompressionStream`, which
    is a dependency to carry for nothing.
    """
    return base64.b64encode(a.astype(np.uint8).tobytes()).decode()


def _spectrogram(x: np.ndarray, fs: int, cols: int, rows: int,
                 f_hi: float) -> dict:
    """Power in dB, quantised to 8 bits between the band's own floor and its peak.

    Referencing the floor to the median cell rather than to a fixed depth below the
    peak is what makes this a picture of the signal instead of a picture of the
    receiver: on a real band most of the plane is noise, and a window wide enough
    to include it lights the whole plane.
    """
    nfft = 1 << int(np.ceil(np.log2(2 * fs / (f_hi / 60))))
    hop = max(1, (x.size - nfft) // cols)
    win = np.hanning(nfft)
    frames = np.array([np.abs(np.fft.rfft(x[i * hop:i * hop + nfft] * win)) ** 2
                       for i in range(cols) if i * hop + nfft <= x.size])
    freqs = np.fft.rfftfreq(nfft, 1 / fs)
    band = frames[:, freqs <= f_hi]
    edges = np.linspace(0, band.shape[1], rows + 1).astype(int)
    binned = np.array([band[:, a:b].mean(axis=1) for a, b in zip(edges, edges[1:])]).T
    db = 10 * np.log10(binned + 1e-9)
    floor, top = float(np.median(db)), float(db.max())
    q = np.clip((db - floor) / (top - floor), 0, 1)
    return {"cols": int(binned.shape[0]), "rows": rows, "f_hi": f_hi,
            "floor_db": round(top - floor, 1),
            "seconds": round(binned.shape[0] * hop / fs, 3),
            "cells": _pack(np.round(q * 255))}


def _psd(x: np.ndarray, fs: int, nfft: int, f_hi: float) -> dict:
    """Welch power spectrum in dB relative to its own peak."""
    win = np.hanning(nfft)
    acc = np.zeros(nfft // 2 + 1)
    n = 0
    for i in range(0, x.size - nfft + 1, nfft // 2):
        acc += np.abs(np.fft.rfft(x[i:i + nfft] * win)) ** 2
        n += 1
    freqs = np.fft.rfftfreq(nfft, 1 / fs)
    db = 10 * np.log10(acc / max(n, 1) + 1e-9)
    keep = freqs <= f_hi
    return {"hz": [round(f, 1) for f in freqs[keep]],
            "db": [round(v - db[keep].max(), 2) for v in db[keep]]}


class _Recorder:
    """The decoder's own symbol decisions, taken on the way past.

    `_psk_block` is where a carrier's differential phases and magnitudes exist as
    numbers; the frame that comes out the far end carries a quality score and not
    the points it was scored on. Subclassing is how the figure gets the same
    array the grader saw rather than a second demodulation of its own.
    """

    def __init__(self, cls, **kw):
        self.blocks: list[tuple[np.ndarray, np.ndarray]] = []
        outer = self

        class Tapped(cls):
            def _psk_block(self, cbin, base, nsym, mod):
                got = super()._psk_block(cbin, base, nsym, mod)
                if got is not None:
                    outer.blocks.append((np.asarray(got[1]), np.asarray(got[2])))
                return got

        self.demod = Tapped(**kw)


def offair() -> dict:
    """Two of the three off-air ARDOP recordings the distribution carries.

    `greeting` is the window `RollingDecoder` held when it read KE8LVA's RMS
    Trimode banner on 7103.5 kHz, 2026-08-05; `conack` is the answer to a connect
    request to the same gateway two days earlier, from the session that failed.
    Between them they are a data frame and a control frame from one transmitter,
    which is the comparison the geometry section cannot make from a specification.

    Every figure is taken over the decoded frame's own span rather than the whole
    fixture. Both recordings open on this station's own transmission leaking into
    a muted receiver, and a spectrum that includes it is a picture of our own
    keying.
    """
    from hfmodem.besra import crc
    from hfmodem.besra.frame.frame import FRAMES
    from hfmodem.besra.phy.demodulator import (_HEADER_LEN, Demodulator,
                                               _body_span)

    out: dict = {}

    fs, au = _wav(FIXTURES / "offair_ke8lva_greeting.wav")
    rec = _Recorder(Demodulator)
    frames = rec.demod.decode(au)
    frame = next(f for f in frames if f.ok)
    span = slice(frame.offset, frame.offset + _HEADER_LEN + _body_span(frame.type))
    body = au[span].astype(float)

    # The walk grades every candidate it reaches and stops at the first frame that
    # validates, so the frame that came out is the last thing graded: its carriers
    # are the final `carriers` blocks, in order. Reading the first block recorded
    # is reading whichever candidate the walk tried first.
    dphase, mag = rec.blocks[-FRAMES[frame.type].carriers]
    step = 1570.796                                     # 90 degrees, in mrad
    nearest = np.round(dphase / step)
    err = dphase - nearest * step
    out["greeting"] = {
        "name": frame.name, "quality": int(frame.quality),
        "payload": frame.payload.decode("ascii", "replace"),
        "bytes": len(frame.payload),
        "seconds": round(body.size / fs, 3),
        "spectrogram": _spectrogram(body, fs, 150, 96, 3000.0),
        "psd": _psd(body, fs, 1024, 3000.0),
        "constellation": {
            "step_mrad": step,
            "symbols": [[round(float(p), 1), round(float(m), 4)]
                        for p, m in zip(dphase, mag / mag.max())],
            "histogram": [int(v) for v in np.bincount((nearest % 4).astype(int),
                                                      minlength=4)],
            "rms_deg": round(float(np.degrees(np.sqrt((err ** 2).mean()) / 1000)), 2),
            "worst_deg": round(float(np.degrees(np.abs(err).max() / 1000)), 2),
        },
    }

    fs, au = _wav(FIXTURES / "offair_ke8lva_conack2000.wav")
    sid = crc.session_id("W9SSJ", "KE8LVA")
    frames = Demodulator(expect_session=lambda: sid).decode(au)
    frame = next(f for f in frames if f.ok)
    span = slice(frame.offset, frame.offset + _HEADER_LEN + _body_span(frame.type))
    body = au[span].astype(float)
    out["conack"] = {
        "name": frame.name, "session_id": int(frame.session_id),
        "timing_ms": int(frame.conack_timing_ms),
        "seconds": round(body.size / fs, 3),
        "spectrogram": _spectrogram(body, fs, 90, 96, 3000.0),
        "psd": _psd(body, fs, 1024, 3000.0),
    }
    return out


def geometry() -> dict:
    """Each waveform's carriers and rungs, read off the modules that place them.

    PACTOR-III and sabir carry their carrier positions as audio frequencies, so
    those are drawn; ARDOP derives its from the carrier count, so that is called.
    kestrel's BW2300 raster is indexed in the receiver's own decimated bins and
    does not convert to an audio frequency here — its ladder is what this takes,
    and the spectrum panel says plainly that VARA is absent from it.
    """
    import hfmodem.besra.frame.frame as bframe
    from hfmodem.besra.phy.demodulator import _carrier_freq
    from hfmodem.kestrel.rx import varahf2300
    from hfmodem.sabir.phy import modem as smodem
    from hfmodem.shrike import spec as pspec

    pactor = {"tones": [round(pspec.TONE0_HZ + i * pspec.TONE_SPACING_HZ, 1)
                        for i in range(pspec.N_CHANNELS)],
              "levels": [{"sl": s.sl, "lit": list(s.channels),
                          "rate": f"{s.code_rate[0]}/{s.code_rate[1]}",
                          "k": s.constraint_length, "net": s.ndr_bps,
                          "crest_db": s.crest_factor_db}
                         for s in pspec.SPEED_LEVELS.values()]}

    seen: dict = {}
    for fd in bframe.FRAMES.values():
        seen.setdefault(fd.name, fd)
    data = [fd for name, fd in seen.items() if fd.k and fd.name.count(".") == 3]
    ardop = {"widths": {str(n): [_carrier_freq(c, n) for c in range(n)]
                        for n in sorted({fd.carriers for fd in data})},
             "frames": sorted(({"name": fd.name, "carriers": fd.carriers,
                                "mod": fd.mod.value, "baud": fd.baud,
                                "k": fd.k, "r": fd.r,
                                "bw": int(fd.name.split(".")[1])}
                               for fd in data),
                              key=lambda f: (f["bw"], f["k"]))}

    sabir = {"gears": [{"rung": name,
                        "lo": round(float(g.carrier_hz[0]), 4),
                        "hi": round(float(g.carrier_hz[-1]), 4),
                        "carriers": g.n_carriers,
                        "constellation": g.constellation, "code": g.code,
                        "repeat": g.repeat}
                       for name in smodem.LADDER
                       if (g := smodem.GEARS.get(name)) is not None]}

    vara = {"levels": [{"level": r.level, "name": r.name, "bpc": r.bpc,
                        "frame_bytes": r.frame_bytes}
                       for r in varahf2300.RECORDS.values()]}
    return {"pactor3": pactor, "ardop": ardop, "sabir": sabir, "vara": vara}


def sabir() -> dict:
    """Current Sabir geometry and error-free airtime, from emitted samples.

    Rates count full link payload codewords, a DATA header, an ACK and two
    250 ms turnarounds. They exclude session setup and host record overhead.
    They are arithmetic upper bounds, not channel measurements.
    """
    from hfmodem.sabir.arq import ArqConfig, LinkModem
    from hfmodem.sabir.arq.profiles import PROFILES
    from hfmodem.sabir.arq.wire import BLOCK_BYTES, CONNECTIONLESS_BYTES, WIRE_VERSION
    from hfmodem.sabir.floor.mfsk import BASE_HZ, GRID, DATA_UNITS, FLOOR_GEARS, FloorModem
    from hfmodem.sabir.phy.modem import FS, GEARS
    from hfmodem.sabir.phy.preamble import preamble_waveform

    modem = LinkModem(ArqConfig())
    rng = np.random.default_rng(20260919)
    floor_s = FloorModem().duration_s(BLOCK_BYTES)
    fast_s = modem.fast.n_samples(1) / FS
    profiles = []
    for profile in PROFILES.values():
        codec = modem.fsm.profile_codec(profile.name)
        coded = np.stack([codec.encode_cw(rng.bytes(codec.data_bytes))
                          for _ in range(profile.frame_cws)])
        wave, symbols = modem.encode_body(profile, coded)
        seconds = len(wave) / FS
        payload = profile.frame_cws * codec.data_bytes
        entry = {"name": profile.name, "id": profile.id,
                 "payload_bytes": payload, "codewords": profile.frame_cws,
                 "symbols": symbols, "body_s": round(seconds, 6),
                 "floor_cycle_bps": round(8 * payload / (seconds + 2 * floor_s + .5), 1),
                 "fast_cycle_bps": None if profile.floor else
                     round(8 * payload / (seconds + 2 * fast_s + .5), 1)}
        if not profile.floor:
            gear = GEARS[profile.name]
            carriers = [round(float(f), 4) for f in gear.carrier_hz]
            entry.update(carriers=carriers, spacing_hz=FS / gear.n_fft,
                         allocation_hz=gear.n_carriers * FS / gear.n_fft,
                         filter_hz=list(gear.passband_hz),
                         constellation=gear.constellation, code=gear.code,
                         repeat=gear.repeat, n_fft=gear.n_fft, cp=gear.cp,
                         psd=_psd(wave.real, FS, 8192, 3200))
        profiles.append(entry)
    controls = {name: {"session_s": round(fm.duration_s(BLOCK_BYTES), 6),
                      "compact_s": round(fm.duration_s(CONNECTIONLESS_BYTES), 6)}
                for name, gear in FLOOR_GEARS.items() if (fm := FloorModem(gear))}
    measurements = REPO / "docs/protocols/sabir/measurements.json"
    return {"profiles": profiles, "wire_version": WIRE_VERSION,
            "session_bytes": BLOCK_BYTES, "compact_bytes": CONNECTIONLESS_BYTES,
            "floor_tones": [BASE_HZ + u * GRID for u in DATA_UNITS],
            "controls": controls, "fast_control_s": round(fast_s, 6),
            "preamble_s": len(preamble_waveform()) / FS,
            "measurements": json.loads(measurements.read_text())
                if measurements.exists() else None}


def kernels() -> dict:
    """shrike's transmit pulse, computed here the same way the modem computes it.

    There are no shipped bytes behind this figure because there is no shipped
    table: `symbol_pulse` is a root-raised cosine evaluated at import, and what
    the modulator convolves with is what this plots.
    """
    from hfmodem.shrike import tablegen

    taps = tablegen.symbol_pulse()
    fs = tablegen.SPS * 100.0
    grid = 4096
    mag = np.abs(np.fft.rfft(taps, grid))
    freqs = np.fft.rfftfreq(grid, 1 / fs)
    db = 20 * np.log10(mag / mag.max() + 1e-12)
    keep = (freqs <= 200)[::4]
    return {"rolloff": round(float(tablegen.ROLLOFF), 6), "sps": int(tablegen.SPS),
            "taps": [round(float(t), 6) for t in taps],
            "response": {"hz": [round(float(f), 2) for f in freqs[::4][keep]],
                         "db": [round(float(v), 2) for v in db[::4][keep]]}}


def raster() -> dict:
    """The PACTOR-1 cycle, to scale, from the constants the receiver keeps time by."""
    from hfmodem.shrike import spec as pspec

    return {"cycle_s": pspec.CYCLE_SHORT_S, "packet_s": pspec.P1_PACKET_S,
            "cs_s": pspec.P1_CS_S}


def figures() -> dict:
    return {"offair": offair(), "geometry": geometry(),
            "kernel": kernels(), "raster": raster()}


def pactor3() -> dict:
    """Every quantity `pactor-explained.html` states, off the modules holding it.

    The page's own figures used to carry two mechanisms the tree does not have. A
    length-19 Zadoff-Chu sequence was drawn as a cross-tone spreading of the data
    field: what exists is `placement.START_PHASE`, Schroeder's quadratic over the
    eighteen channels, applied once to the packet's single phase-reference symbol
    -- the same quadratic ramp, on one symbol rather than the whole field, and the
    N is the channel count. And the header block was given a K=7 `(0o161, 0o172)`
    FEC pair, which `placement.CONV_GENERATORS` records as a narrow search's
    coincidence that does not decode; the header block carries the published
    constant and variable header codewords and is matched-filter detected, so
    there is no FEC field there to name.
    """
    from hfmodem.shrike import coding, p3frame, placement, spec, unknowns

    def octal(g: int) -> str:
        return f"0o{g:o}"

    gens = unknowns.U1_GENERATORS.value
    levels = []
    for sl, s in spec.SPEED_LEVELS.items():
        path = placement.SPEED_PATHS[sl]
        levels.append({"sl": s.sl, "channels": list(s.channels),
                       "bits_per_symbol": s.bits_per_symbol,
                       "k": s.constraint_length,
                       "rate": f"{s.code_rate[0]}/{s.code_rate[1]}",
                       "pdr": s.pdr_bps, "ndr": s.ndr_bps,
                       "crest_db": s.crest_factor_db,
                       "payload_short": s.payload_short,
                       "payload_long": s.payload_long,
                       "generators": [octal(g) for g in gens[s.constraint_length]],
                       "stride": path.stride, "n_buf": path.n_buf,
                       "puncture": [list(m) for m in path.puncture.mask]})

    return {
        "physical": {"chan0_hz": spec.TONE0_HZ, "spacing_hz": spec.TONE_SPACING_HZ,
                     "n_channels": spec.N_CHANNELS, "baud": spec.SYMBOL_RATE_BD,
                     "vh": list(spec.VH_CHANNELS), "centre_hz": spec.CENTER_FREQ_HZ,
                     "emission": spec.EMISSION_DESIGNATOR,
                     "hi_hz": spec.TONE0_HZ + spec.TONE_SPACING_HZ * (spec.N_CHANNELS - 1)},
        "levels": levels,
        "control": {"words": [f"{w:05X}" for w in spec.CONTROL_SIGNALS],
                    "names": list(spec.CS_NAMES), "bits": spec.CS_BITS_PER_TONE},
        "packet": {"header_symbols": p3frame.HEADER_SYMBOLS,
                   "data_offset": p3frame.DATA_OFFSET,
                   "rows_short": placement.FRAME_SYMBOLS,
                   "rows_long": placement.LONG_ROWS,
                   "packet_s": placement.PACKET_S,
                   "constant_headers": len(spec.CONSTANT_HEADERS),
                   "variable_headers": len(spec.VARIABLE_HEADERS)},
        "cycle": {"short_s": spec.CYCLE_SHORT_S, "long_s": spec.CYCLE_LONG_S,
                  "short_longpath_s": spec.CYCLE_SHORT_LONGPATH_S,
                  "long_longpath_s": spec.CYCLE_LONG_LONGPATH_S,
                  "pulse_slot_s": spec.PULSE_SLOT_S, "cs_window_s": spec.CS_WINDOW_S},
        "coding": {"tx_generators": [octal(g) for g in placement.CONV_GENERATORS],
                   "crc_poly": f"0x{spec.CRC_POLY:04X}",
                   "puncture_3_4": [list(m) for m in coding.PUNCTURE_3_4.mask],
                   "puncture_8_9": [list(m) for m in coding.PUNCTURE_8_9.mask],
                   "interleave": "per-path stride (unknowns.U3_INTERLEAVER: "
                                 f"{unknowns.U3_INTERLEAVER.status})"},
        "phase": {"dibit_deg": [round(float(d), 3) for d in
                                np.degrees(np.angle(p3frame.DIBIT_PHASOR))],
                  "bit_deg": [round(float(np.degrees(placement.BIT_PHASE[b])), 3)
                              for b in (0, 1)],
                  "start_deg": [round(float(d), 3) for d in
                                np.degrees(placement.START_PHASE) % 360.0],
                  "pattern_a_deg": [round(float(d), 3) for d in
                                    np.degrees(np.angle(p3frame.PATTERN_A))]},
    }


def vara() -> dict:
    """Every quantity `vara-explained.html` states, off kestrel's own receivers.

    The page was built around a separate narrowband 46.875-baud 16-tone caller-ID
    burst on FFT-1024 bins 9-24, and around a BW2300 of 65 carriers on FFT-2048
    bins 34-98. Neither is a waveform. `RECORDS[3]` is the whole of it: one lit bin
    per 512-sample column in a sixteen-bin span, and the caller identity is what
    the initiator's first such burst carries. The 65-carrier reading is what a
    2048-point window makes of four consecutive 512-sample columns, which is why
    the bin span here is computed off `dw50` rather than named.
    """
    from hfmodem.kestrel.rx import varahf500 as bw500
    from hfmodem.kestrel.rx import varahf2300 as bw2300
    from hfmodem.kestrel.vara import vara_frames as vframes
    from hfmodem.kestrel.vara import vara_mfsk as vmfsk

    r = bw2300.RECORDS[bw2300.BASE_LEVEL]
    ref_cols, _, data_cols, _ = bw2300._column_roles(bw2300.BASE_LEVEL)
    bin_hz = bw2300.FS / r.dw50

    def burst(k) -> dict:
        n = len(k.preamble) + k.n_payload
        return {"name": k.name, "symbols": n,
                "seconds": round(n * vmfsk.HOP / vmfsk.FS, 4),
                "seed_off": k.seed_off, "preadv": k.preadv,
                "preamble": list(k.preamble), "n_payload": k.n_payload}

    return {
        "mfsk": {"fs": vmfsk.FS, "nfft": vmfsk.NFFT, "hop": vmfsk.HOP,
                 "wola_n": vmfsk.WOLA_N, "stride": vmfsk.STRIDE,
                 "hz_per_bin": round(vmfsk.FS / vmfsk.NFFT, 6),
                 "bursts": {name: burst(k) for name, k in
                            (("CR", vframes.CR), ("RESP", vframes.CONNECT_RESPONSE),
                             ("RELEASE", vframes.SESSION_TURN_RELEASE),
                             ("DISCONNECT", vframes.SESSION_DISCONNECT_REQ))}},
        "bw2300": {"base_level": bw2300.BASE_LEVEL, "law": r.law, "bpc": r.bpc,
                   "dw50": r.dw50, "cp": r.cp,
                   "baud": round(bw2300.FS / r.dw50, 4),
                   "hz_per_bin": round(bin_hz, 4),
                   "first_bin": r.first_bin, "span": r.span, "stride": r.stride,
                   "lo_hz": round(r.first_bin * bin_hz, 2),
                   "hi_hz": round((r.first_bin + r.span - 1) * bin_hz, 2),
                   "columns": r.ncols, "data_columns": int(data_cols.size),
                   "reference_columns": int(ref_cols.size),
                   "lead_blocks": r.lead, "n_info": r.n_info, "coded": r.coded,
                   "frame_bytes": r.frame_bytes,
                   "payload_bytes": bw2300.payload_bytes(bw2300.BASE_LEVEL),
                   "blocks_s": round((r.lead + r.ncols) * r.dw50 / bw2300.FS, 3),
                   "levels": [{"level": rec.level, "name": rec.name, "law": rec.law,
                               "bpc": rec.bpc, "span": rec.span,
                               "frame_bytes": rec.frame_bytes, "dw50": rec.dw50}
                              for rec in bw2300.RECORDS.values()],
                   "keyable": list(bw2300.KEYABLE_LEVELS)},
        "bw500": {"subbands": [[i, hz] for i, hz in bw500.SUBBANDS],
                  "samples_per_symbol": bw500.H, "columns": bw500.NSYM,
                  "coded": bw500.CODED, "info_bits": bw500.N_SRC,
                  "payload_bytes": bw500.FRAME_PAYLOAD, "first_column": bw500.OFF},
    }


def _frame_waterfall(samples: np.ndarray, fs: int) -> dict:
    """Windowed power of a rendered frame, 0–3000 Hz, relative to its peak."""
    nfft, steps = 4096, 192
    padded = np.pad(samples.astype(np.float64), (nfft // 2, nfft // 2))
    centers = np.linspace(0, len(samples) - 1, steps).astype(int)
    windows = np.array([padded[i:i + nfft] for i in centers])
    power = np.abs(np.fft.rfft(windows * np.hanning(nfft), axis=1)) ** 2
    power = power[:, :int(3000 * nfft / fs) + 1]
    peak = max(float(power.max()), np.finfo(float).tiny)
    db = 10 * np.log10(np.maximum(power / peak, 1e-12))
    cells = np.round(np.clip((db + 60) / 60, 0, 1) * 255).astype(np.uint8)
    return {"width": cells.shape[1], "height": steps, "floor_db": -60,
            "nfft": nfft, "cells": _pack(cells)}


def ardop() -> dict:
    """HF data modes, rendered duration, and a real decoded gateway frame.

    Even/odd twins share geometry; show the even member once. The 600-baud
    FM modes are deliberately outside this HF guide. Duration is the actual
    sample count from the transmitter, including its default leader/filter/tail,
    rather than a worksheet estimate or an ARQ throughput claim.
    """
    from hfmodem.besra.dsp.detect import FSK_TONES, LEADER_TONES
    from hfmodem.besra.frame.frame import FRAMES, Mod
    from hfmodem.besra.phy.demodulator import _carrier_freq
    from hfmodem.besra.phy.modulator import (
        DEFAULT_LEADER_MS, DEFAULT_TRAILER_MS, SAMPLE_RATE, render_frame,
    )

    modes = []
    for fd in FRAMES.values():
        if not fd.name.endswith(".E") or fd.baud == 600:
            continue
        payload = bytes(i % 256 for i in range(fd.net_payload))
        samples = render_frame(fd.type, payload, session_id=0x42)
        fsk = fd.mod is Mod.FSK4
        modes.append({
            "type": fd.type, "name": fd.name.removesuffix(".E"),
            "bw": int(fd.name.split(".")[1]), "mod": fd.mod.value,
            "carriers": fd.carriers, "baud": fd.baud, "k": fd.k, "r": fd.r,
            "payload": fd.net_payload, "samples": len(samples),
            "seconds": len(samples) / SAMPLE_RATE,
            "waterfall": _frame_waterfall(samples, SAMPLE_RATE),
            "frequencies": list(FSK_TONES[fd.baud]) if fsk else
                           [_carrier_freq(c, fd.carriers) for c in range(fd.carriers)],
        })
    greeting = offair()["greeting"]
    return {"modes": modes, "sample_rate": SAMPLE_RATE,
            "leader_ms": DEFAULT_LEADER_MS, "trailer_ms": DEFAULT_TRAILER_MS,
            "leader_tones": list(LEADER_TONES),
            "greeting": {k: greeting[k] for k in
                         ("name", "quality", "payload", "bytes", "seconds", "psd")}}


PAGES = {"flock-compared.html": figures,
         "pactor-explained.html": pactor3,
         "vara-explained.html": vara,
         "ardop-explained.html": ardop,
         "sabir-explained.html": sabir}


def block(data: dict) -> str:
    return f"{BEGIN}\nconst FIG = {json.dumps(data, sort_keys=True)};\n{END}"


def splice(path: Path, page: str, made: str) -> str:
    head, _, rest = page.partition(BEGIN)
    _, _, tail = rest.partition(END)
    if not rest or not tail:
        raise SystemExit(f"{path} has no generated block to replace")
    return head + made + tail


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="report drift and change nothing")
    a = ap.parse_args(argv)

    stale = []
    for name, make in PAGES.items():
        path = Path(__file__).with_name(name)
        rel = path.relative_to(REPO)
        if not path.exists():
            print(f"{rel} is not in this tree; not checked")
            continue
        page = path.read_text(encoding="utf-8")
        made = splice(path, page, block(make()))
        if made == page:
            print(f"{rel} is current")
        elif a.check:
            stale.append(str(rel))
        else:
            path.write_text(made, encoding="utf-8")
            print(f"{rel} rewritten")

    if stale:
        print(f"out of date, run docs/viz/build.py: {', '.join(stale)}",
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
