# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2026 Saul St John (W9SSJ)

"""Normative known-answer test vectors (SPEC.md §KAT).

These byte images are the conformance oracle: an independent sabir
implementation that reproduces them is wire-compatible. They are generated by
the reference encoder and pinned here; changes to them require a matching specification update. Waveform conformance is asserted as
a byte-exact round trip and a fixed sample count rather than a float digest, so
it holds across platforms and NumPy versions.
"""

import hashlib

import numpy as np
import pytest

from hfmodem.sabir import compress
from hfmodem.sabir.arq import wire
from hfmodem.sabir.fec import CODES, QCLDPC
from hfmodem.sabir.floor.mfsk import FloorModem
from hfmodem.sabir.frame.codec import crc16, pn9

# canonical session identity used throughout the vectors (NEGOTIATION.md §9)
_CALLER, _CALLEE = "W1AW", "K6XYZ"
_TAG = 0x81
_FULL = wire.capabilities(range(3, 7 + 1), wire.FASTCTL | wire.PBACK | wire.LOADING | wire.DEFLATE)


def test_kat_session_identity():
    assert _FULL == 0x0F0000F8                                # ceiling 7 + 4 features


def test_kat_control_block_images():
    """The 44-byte session and 22-byte connectionless block images (SPEC.md §KAT)."""
    vec = {
        wire.Control.connect(_TAG, _FULL, _CALLER, destination=_CALLEE):
            "0102000000000000008100000f0000f85731415720202020202020204b3658595a202020202020200000b908",
        wire.Control.connect(_TAG, _FULL, _CALLEE, ack=True, destination=_CALLER):
            "0202000000000000008100000f0000f84b3658595a202020202020205731415720202020202020200000cc2d",
        wire.Caps.build(_TAG, wire.pack_tlvs([(wire.GEARSET, b"\x01\x00\xff\xff")]), 1, 0):
            "0a0200000000000000811001040100ffff00000000000000000000000000000000000000000000000000b9fa",
        wire.Control(wire.DATA, _TAG, seq=7, gear=4,
                     mask=wire.cw_mask([0, 1, 2]),
                     aux=wire.data_aux(120, 3, (0,) * 8)):
            "0302000000000000008100000007000004070000000000000000780300000000000000000000000000007fdf",
        wire.Control(wire.ACK, _TAG, seq=7, mask=wire.cw_mask([0, 1, 2]),
                     aux=wire.ack_aux(None)):
            "04020000000000000081000000070000000700000000000000ffffffffffffffff000000000000000000f0d8",
        wire.Beacon.build(_FULL, _CALLER, profile=1):
            "30000f0000f85731415720202020202020200100f1cc",
    }
    for block, expected in vec.items():
        assert block.pack().hex() == expected, type(block).__name__
        # every image is exactly one block and its CRC verifies
        buf = block.pack()
        assert len(buf) == (wire.CONNECTIONLESS_BYTES if isinstance(block, wire.Beacon) else wire.BLOCK_BYTES)
        assert crc16(buf[:-2]) == int.from_bytes(buf[-2:], "big")


def test_kat_vectors_decode_back():
    """Each control image round-trips through unpack to the same view."""
    c = wire.Control.unpack(wire.Control.connect(_TAG, _FULL, _CALLER, destination=_CALLEE).pack())
    assert c.type == wire.CONNECT and wire.supported_profiles(c.capability_word) == list(range(3, 8)) and c.call == _CALLER
    b = wire.Control.unpack(wire.Beacon.build(_FULL, _CALLER, profile=1).pack())
    assert type(b) is wire.Beacon and b.call == _CALLER and b.profile == 1


# SPEC.md §KAT FEC vectors: SHA-256 of each §7.1.5 base matrix, serialized
# row-major as mb*nb big-endian int16 with -1 for an absent entry. The grids
# in fec/ldpc.py are data; this is what keeps them and the spec from drifting
# apart — a mismatch here is a wire-format change.
_GRID_SHA = {
    "r13": "210ced6a426aa0f1bc6ec764d6ab937851f7fe17fb5ecce08f7fd7154e15c996",
    "r12": "171607af29cb523f77a155e0fc4628474de4c56f15c26c9e7171b6390b8cbf59",
    "r34": "10fb0b6eb57329ed60c20bc45752d1a7233bd900f651469a9d72b7faafb290cc",
    "r56": "c7d59fb5be3b1c6807bfc1a0dd0ecefc00cb030613ed3ff86b609f22a89f9b38",
}

# SPEC.md §KAT encoder vectors: information vector = first k outputs of the
# PN9 sequence, codeword packed MSB-first into n/8 bytes.
_CODEWORD_SHA = {
    "r13": ("06051825430b9dc0be1610ceca910c961294e7538ab834ce36c97987128021f3",
            "5d0b03c5021036fd"),
    "r12": ("1f0584c9d3597093f27d8a877b0026c4dabfb84f0aa0fcf81b50d838e2ff5f87",
            "0eadfb52116d5204"),
    "r34": ("c674868b36e7f768d7a6e21a4d2bf95efadd838559279234dc3e234c97583d13",
            "2c5ca989216a5c4e"),
    "r56": ("ee50383886eb74ac71d366ab898ddd9dec2ad7f50d9d770be3b0481d3e99a1ad",
            "3d0c51c9bdf792be"),
}


@pytest.mark.parametrize("rate", list(CODES))
def test_kat_ldpc_base_matrix(rate):
    grid = CODES[rate]
    assert grid.dtype == np.int16
    digest = hashlib.sha256(grid.astype(">i2").tobytes()).hexdigest()
    assert digest == _GRID_SHA[rate]


@pytest.mark.parametrize("rate", list(CODES))
def test_kat_ldpc_codeword(rate):
    code = QCLDPC(rate)
    cw = np.packbits(code.encode(pn9(code.k)))
    sha, parity_head = _CODEWORD_SHA[rate]
    assert hashlib.sha256(cw.tobytes()).hexdigest() == sha
    assert cw[code.k // 8:code.k // 8 + 8].tobytes().hex() == parity_head


def test_kat_payload_records():
    """SPEC.md §KAT record vectors. Encoding is pinned in the RAW direction
    only -- any RFC 1951 stream is a valid DEFLATE body, so the compressed
    vector pins the decode direction, which is what interoperates."""
    assert compress.pack(b"sabir").hex() == '1000002573616269726fbd6b834be756614d476c69400d4e27e26f73a31272aa24b18fd0401100a50e'
    u = compress.Unpacker()
    deflated = bytes.fromhex("1100002a2b4e4cca2c5228462701")
    deflated += hashlib.sha256(deflated).digest()
    assert list(u.feed(deflated)) == [b"sabir sabir sabir sabir"]
    # unknown flag: never delivered, even though the record self-delimits
    u = compress.Unpacker()
    with pytest.raises(compress.UnknownRecordFlag):
        list(u.feed(bytes.fromhex("020000057361626972")))


def test_kat_floor_waveform_conformance():
    """A control block on the floor waveform: fixed sample count and byte-exact
    demodulation (the reproducible waveform oracle, SPEC.md §Verification)."""
    fm = FloorModem()
    block = wire.Control.connect(_TAG, _FULL, _CALLER, destination=_CALLEE).pack()
    wav = fm.transmit(block)
    assert wav.size == 418560                           # normative sample count
    raw, _ = fm.receive(wav, wire.BLOCK_BYTES)
    assert raw == block                                 # exact, no channel


def test_kat_ofdm_gear_roundtrip():
    """The workhorse OFDM gear encodes and demodulates byte-exact in loopback
    (per-gear conformance is swept in test_m1/m2; this pins the reference)."""
    from hfmodem.sabir.phy import GEARS, Phy
    phy = Phy(GEARS["workhorse"])
    rng = np.random.default_rng(0)
    bits = rng.integers(0, 2, phy.capacity(8)).astype(np.int8)
    rx = phy.from_audio(phy.to_audio(phy.transmit(bits)))
    _, llr, _ = phy.receive(rx, n_symbols=8)
    assert ((llr < 0).astype(np.int8) == bits).all()


def test_kat_payload_codeword():
    from hfmodem.sabir.frame import FrameCodec
    packed = np.packbits(FrameCodec(QCLDPC('r12')).encode_cw(b'sabir'))
    assert packed[:8].tobytes().hex() == 'c7125d58e367f069'
    assert hashlib.sha256(packed.tobytes()).hexdigest() == '26c9d300077a29e620eb4596f2019b04fc36066aba5b2cc5bc62dab2f9684399'
